version: '3.8'
services:
  tsed_dev:
    build:
      context: .
      dockerfile: ./docker/Tsed_Dev_Dockerfile
    image: moveyourtable.azurecr.io/gateway
    ports:
      - "${TSED_EXPOSE_PORT}:${TSED_PORT}"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    stdin_open: true  # -i
    tty: true         # -t
    container_name: Gateway-Dev
    environment:
      - TSED_PORT=${TSED_PORT}
      - BACK_END_ENDPOINT=${DOCKER_BACK_END_ENDPOINT}
      - BACK_END_PORT=${DOCKER_BACK_END_PORT}
      - AUTOMATION_API_ENDPOINT=${DOCKER_AUTOMATION_API_ENDPOINT}
      - AUTOMATION_API_PORT=${DOCKER_AUTOMATION_API_PORT}
    networks:
      default:
        aliases:
          - tsed
          - tsed_dev
  tsed_prod:
    container_name: Gateway-Prod
    build:
      context: .
      dockerfile: ./docker/Tsed_Prod_Dockerfile
    image: myt/gateway:prod
    ports:
      - "${TSED_EXPOSE_PORT}:${TSED_PORT}"
    environment:
      - TSED_PORT=${TSED_PORT}
      - BACK_END_ENDPOINT=${DOCKER_BACK_END_ENDPOINT}
      - BACK_END_PORT=${DOCKER_BACK_END_PORT}
      - AUTOMATION_API_ENDPOINT=${DOCKER_AUTOMATION_API_ENDPOINT}
      - AUTOMATION_API_PORT=${DOCKER_AUTOMATION_API_PORT}
    networks:
      default:
        aliases:
          - tsed
          - tsed_prod

networks:
  default:
    name: myt
