version: '3.8'
services:
  tsed:
    build:
      context: .
      dockerfile: /docker/Dev_Dockerfile
    image: myt/gateway:1.0
    ports:
      - "${TSED_PORT}:8081"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true  # -i
    tty: true         # -t
    container_name: Gateway-Dev
    environment:
      - BACK_END_ENDPOINT=nest
      - AUTOMATION_API_ENDPOINT=automate
  mongodb:
    image: myt/back-end-db:1.0
    container_name: MongoDB-Dev
    build: 
      context: /submodules/back-end
      dockerfile: /docker/Mongo_Dockerfile
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - ${MONGO_PORT}:27017
  nest:
    image: myt/back-end:1.0
    restart: always
    container_name: Back-End-Dev
    build:
      context: /submodules/back-end
      dockerfile: /docker/Nest_Dockerfile
    depends_on:
      - mongodb_dev
      - rabbimq_dev
    environment:
      - AUTOMATION_API_ENDPOINT=automate
      - GATEWAY_API_ENDPOINT=tsed
  rabbitmq:
    image: rabbitmq:3.8.25-alpine
    restart: always
    container_name: RabbitMQ-Dev
    ports:
      - ${RABBITMQ_PORT}:5672
  automate:
    image: myt/automation-api:1.0
    container_name: Automate-API-Dev
    build:
      context: /submodules/automateapi
      dockerfile: /Dockerfile
    environment:
      - BACK_END_ENDPOINT=nest
      - GATEWAY_API_ENDPOINT=tsed

volumes:
  node_modules: {}
