version: '3.8'
services:
  tsed:
    build:
      context: .
      dockerfile: /docker/Dev_Dockerfile
    image: node:14-alpine
    ports:
      - "${TSED_PORT}:8081"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    stdin_open: true  # -i
    tty: true         # -t
    container_name: TS.ed
  rabbitmq:
    image: rabbitmq:3.8.25-alpine
    restart: always
    container_name: RabbitMQ
    ports:
      - ${RABBITMQ_PORT}:5672

volumes:
  node_modules: {}
