version: '3.8'
services:
  tsed_dev:
    profiles: ["container-dev"]
    build:
      context: .
      dockerfile: ./docker/Dev_Dockerfile
    image: myt/gateway:1.0
    ports:
      - "${TSED_PORT}:8080"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    stdin_open: true  # -i
    tty: true         # -t
    container_name: Gateway-Dev
    environment:
      - BACK_END_ENDPOINT=nest
      - AUTOMATION_API_ENDPOINT=automate
  rabbitmq_dev:
    profiles: ["container-dev", "local-dev"]
    image: rabbitmq:3.9.10-management-alpine
    restart: always
    container_name: RabbitMQ-Dev
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_MANAGEMENT_PORT}:15672
