version: '3.8'
services:
  tsed_dev:
    build:
      context: .
      dockerfile: ./docker/Tsed_Dev_Dockerfile
    image: myt/gateway:dev
    ports:
      - "${TSED_PORT}:8080"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    stdin_open: true  # -i
    tty: true         # -t
    container_name: Gateway-Dev
    environment:
      - TSED_PORT=8080
      - BACK_END_ENDPOINT=nest_staging
      - AUTOMATION_API_ENDPOINT=rust_prod
    networks:
      default:
        aliases:
          - "tsed"
  tsed_prod:
    container_name: Gateway-Prod
    build:
      context: .
      dockerfile: ./docker/Tsed_Prod_Dockerfile
    image: myt/gateway:prod
    ports:
      - "${TSED_PORT}:8080"
    environment:
      - TSED_PORT=8080
      - BACK_END_ENDPOINT=nest_staging
      - AUTOMATION_API_ENDPOINT=rust_prod
    networks:
      default:
        aliases:
          - "tsed"

networks:
  default:
    name: myt
